//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int RentalCode { get; set; }
        public System.DateTime PickupDate { get; set; }
        public System.DateTime EstimatedReturnDate { get; set; }
        public System.DateTime ActualReturnDate { get; set; }
        public int UserID { get; set; }
        public int VehicleID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
