//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Rentals = new HashSet<Rental>();
        }
    
        public int VehicleID { get; set; }
        public int VehicleTypeID { get; set; }
        public int Mileage { get; set; }
        public bool RentingProper { get; set; }
        public bool RentingAvailibility { get; set; }
        public int RegistrationNumber { get; set; }
        public int BranchID { get; set; }
        public string CarImage { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental> Rentals { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
